let background_pointed = "#80c0ff"
let text_pointed = "black"
let background_pointed2 = "#4060a0"
let text_pointed2 = "white"
let background_selected = "#2040c0"
let text_selected = "white"
let background_disabled = "#808080"
let text_disabled = "black"
